version: '3.1'

networks:
  kennels_net:
    external: true

services:
  nginx:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - kennels
    networks:
      - kennels_net
  dogs:
    build: ./services/dogs
    environment:
     - OTEL_SERVICE_NAME=dogs
     - OTEL_TRACES_EXPORTER=otlp
     - OTEL_EXPORTER_OTLP_ENDPOINT=http://collector:4317
     - OTEL_NODE_RESOURCE_DETECTORS=env,host,os
     - OTEL_EXPORTER_OTLP_PROTOCOL=grpc 
     - OTEL_EXPORTER_OTLP_INSECURE=true
     #- NODE_OPTIONS="--require @opentelemetry/auto-instrumentations-node/register"
    networks:
      - kennels_net
  inventory:
    build: ./services/inventory
    environment:
     - OTEL_SERVICE_NAME=inventory
     - OTEL_TRACES_EXPORTER=otlp
     - OTEL_EXPORTER_OTLP_ENDPOINT=http://collector:4317
     - OTEL_NODE_RESOURCE_DETECTORS=env,host,os
     - OTEL_EXPORTER_OTLP_PROTOCOL=grpc 
     - OTEL_EXPORTER_OTLP_INSECURE=true
     #- NODE_OPTIONS="--require @opentelemetry/auto-instrumentations-node/register"
    networks:
      - kennels_net
  kennels:
    build: ./services/kennels
    environment:
     - OTEL_SERVICE_NAME=kennels
     - OTEL_TRACES_EXPORTER=otlp
     - OTEL_EXPORTER_OTLP_ENDPOINT=http://collector:4317
     - OTEL_NODE_RESOURCE_DETECTORS=env,host,os
     - OTEL_EXPORTER_OTLP_PROTOCOL=grpc 
     - OTEL_EXPORTER_OTLP_INSECURE=true
     #- NODE_OPTIONS="--require @opentelemetry/auto-instrumentations-node/register"
    networks:
      - kennels_net