volumes:
  grafana_data: {}
  tempo_data: {}

networks:
  kennels_net:
    external: true

services:
  k6:
    image: grafana/k6:latest
    volumes:
      - ./k6/load_test.js:/scripts/load_test.js
    command: ["run", "/scripts/load_test.js"]
    networks:
      - kennels_net
  
  collector: # Exposes 4317 (grpc) and 4318 (http)
    image: otel/opentelemetry-collector:latest
    command: '--config /etc/otel-config.yaml'
    volumes:
      - ./obs/otel-config.yaml:/etc/otel-config.yaml
    networks:
      - kennels_net
  # Stack Obs
  grafana:
    build: ./obs/grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - "GF_DEFAULT_APP_MODE=development"
      - "GF_LOG_LEVEL=debug"
      - "GF_SERVER_CERT_FILE=/etc/grafana/grafana.crt" # adjust to match your domain name
      - "GF_SERVER_CERT_KEY=/etc/grafana/grafana.key" # adjust to match your domain name
      - "GF_SERVER_PROTOCOL=https"
      - "GF_SECURITY_ADMIN_USER=admin"
      - "GF_SECURITY_ADMIN_PASSWORD=admin"
      - "GF_FEATURE_TOGGLES_ENABLE=traceqlEditor traceQLStreaming metricsSummary"
    networks:
      - kennels_net
  
  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./obs/tempo.yaml:/etc/tempo.yaml
      - tempo_data:/var/tempo
    ports:
      - "14268:14268"  # jaeger ingest
      - "3200:3200"   # tempo
      - "9095:9095" # tempo grpc
      - "4317:4317"  # otlp grpc
      - "4318:4318"  # otlp http
      - "9411:9411"   # zipkin
    networks:
      - kennels_net
  prometheus:
    image: prom/prometheus:v2.34.0
    restart: unless-stopped
    volumes:
      - ./obs/prometheus.yaml:/etc/prometheus/prometheus.yaml
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--enable-feature=remote-write-receiver"
    networks:
      - kennels_net