version: '3.1'

networks:
  net:
    driver: bridge

services:
  nginx:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - kennels
    networks:
      - net
  
  dogs:
    build: ./services/dogs
    environment:
     - OTEL_SERVICE_NAME=dogs
    networks:
      - net
  inventory:
    build: ./services/inventory
    environment:
     - OTEL_SERVICE_NAME=inventory
    networks:
      - net
  kennels:
    build: ./services/kennels
    environment:
     - OTEL_SERVICE_NAME=kennels
    networks:
      - net