volumes:
  grafana_data: {}
  tempo_data: {}

networks:
  kennels_net:
    external: true

services:
  k6:
    image: grafana/k6:latest
    volumes:
      - ./obs/k6/load_test.js:/scripts/load_test.js
    command: ["run", "/scripts/load_test.js"]
    networks:
      - kennels_net
  
  collector: # Exposes 4317 (grpc) and 4318 (http)
    image: otel/opentelemetry-collector:latest
    command: '--config /etc/otel-config.yaml'
    volumes:
      - ./obs/otel-config.yaml:/etc/otel-config.yaml
    networks:
      - kennels_net
  # Stack Obs
  grafana:
    image: grafana/grafana:10.4.2
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor traceQLStreaming metricsSummary
    networks:
      - kennels_net
  
  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./obs/tempo.yaml:/etc/tempo.yaml
      - tempo_data:/var/tempo
    ports:
      - "14268:14268"  # jaeger ingest
      - "3200:3200"   # tempo
      - "9095:9095" # tempo grpc
      - "4317:4317"  # otlp grpc
      - "4318:4318"  # otlp http
      - "9411:9411"   # zipkin
    networks:
      - kennels_net
  prometheus:
    image: prom/prometheus:v2.34.0
    restart: unless-stopped
    volumes:
      - ./obs/prometheus.yaml:/etc/prometheus/prometheus.yaml
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--enable-feature=remote-write-receiver"
    networks:
      - kennels_net